In [10]:
%ls datasets/

adult.csv                  census.csv     movies.csv
airline_data.csv           coches.csv     nhanes_2015_2016.csv
antropometria00.csv        cwurData.csv   pokemon.csv
antropometria-dataset.csv  data.csv       reg_data.csv
Book3.csv                  headbrain.csv  sample_pivot.csv
Canada.xlsx                mic2.xlsx      tips.csv
Cartwheeldata.csv          mic.xlsx       weight-height.csv

In [13]:
datafile = 'datasets/Cartwheeldata.csv'

In [4]:
import pandas as pd

In [18]:
df = pd.read_csv(datafile)
df.tail(1)

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
24,25,23,F,1,Y,1,65.0,63.0,67,N,0,3

In [19]:
type(df)

pandas.core.frame.DataFrame

In [20]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [22]:
type(df.columns)

pandas.core.indexes.base.Index

In [24]:
x=df.columns

In [29]:
x
type(x)

pandas.core.indexes.base.Index

In [32]:
a=list(x)

In [38]:
a.sort()
a

['Age',
 'CWDistance',
 'Complete',
 'CompleteGroup',
 'Gender',
 'GenderGroup',
 'Glasses',
 'GlassesGroup',
 'Height',
 'ID',
 'Score',
 'Wingspan']

In [43]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [ ]:
#Loc and iloc

In [48]:
vars = df.loc[:3, 'Wingspan': 'CompleteGroup']
vars

   Wingspan  CWDistance Complete  CompleteGroup
0      61.0          79        Y              1
1      60.0          70        Y              1
2      64.0          85        Y              1
3      63.0          87        Y              1

In [50]:
vars = df.iloc[2:6, 2:5]
vars

  Gender  GenderGroup Glasses
2      F            1       Y
3      F            1       N
4      M            2       N
5      M            2       N